In [145]:
# https://judge.nitro-ai.org/competitions/nitro/pre-iaio-2026/3/view

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
from sklearn.decomposition import PCA

In [146]:
train = pd.read_csv("/kaggle/input/datasets/abukanabek/preiaio-2026-3/train_data.csv")
subm = pd.read_csv("/kaggle/input/datasets/abukanabek/preiaio-2026-3/sample_output.csv")

train.shape, subm.shape

((420, 12), (421, 3))

In [147]:
train.head()

,subtaskID,datapointID,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10
0,2,1,18.845863,15.432435,-4.888494,-11.196174,1.408862,-17.684394,3.231677,-1.476026,-4.660365,-15.947031
1,2,2,-4.746868,-5.971201,4.346016,-6.677494,1.910919,7.616225,-0.325792,-8.837899,-10.356530,-4.331975
2,2,3,2.908971,-19.955318,-11.212437,9.294100,-1.321366,-5.237313,-13.585740,-10.797363,-20.217986,-1.012807
3,2,4,-12.374266,1.094085,13.286408,3.131845,-6.065034,4.559042,-4.590903,-6.946004,-11.543627,-17.518288
4,2,5,3.261330,-12.511136,9.240270,-1.849021,-5.227230,10.490092,-7.043437,-14.084613,-15.566292,6.060100

In [148]:
def choose(X, available, n_subspace_dims=3, epochs=2000, to_keep=20):
    best_choice = None 
    for epoch in tqdm(range(epochs), leave=False):
        sample_indices = np.random.choice(len(available), size=4, replace=False)
        pca = PCA(n_components=n_subspace_dims)

        pca.fit(X[available[sample_indices]])

        reconstruction = pca.inverse_transform(pca.transform(X))

        residuals = np.linalg.norm(X - reconstruction, axis=1)

        new_available = np.argsort(residuals)[:to_keep]
        res_sum = residuals[new_available].sum()
        if best_choice is None or res_sum < best_choice[1]:
            best_choice = (pca, res_sum, new_available)
    print(f'Best score here: {best_choice[1]:.5f}')
    # print(f'New available: {[x.item() for x in sorted(new_available)]}')
    return best_choice

In [149]:
X = train[[f'X{i}' for i in range(1, 10+1)]].values
available = np.arange(X.shape[0])
choice = None

for _ in range(10):
    best_choice = choose(X, available)
    if choice is None or choice[1] > best_choice[1]:
        choice = best_choice
        available = best_choice[2]

  0%|          | 0/2000 [00:00<?, ?it/s]

Best score here: 124.27266

  0%|          | 0/2000 [00:00<?, ?it/s]

Best score here: 71.34908

  0%|          | 0/2000 [00:00<?, ?it/s]

Best score here: 50.09067

  0%|          | 0/2000 [00:00<?, ?it/s]

Best score here: 50.85397

  0%|          | 0/2000 [00:00<?, ?it/s]

Best score here: 52.77522

  0%|          | 0/2000 [00:00<?, ?it/s]

Best score here: 52.41260

  0%|          | 0/2000 [00:00<?, ?it/s]

Best score here: 49.94506

  0%|          | 0/2000 [00:00<?, ?it/s]

Best score here: 49.94506

  0%|          | 0/2000 [00:00<?, ?it/s]

Best score here: 49.94506

  0%|          | 0/2000 [00:00<?, ?it/s]

Best score here: 50.09067

In [150]:
subm.iloc[available + 1, 2] = 1

subm.to_csv("submission.csv", index=False)

subm

     subtaskID  datapointID  answer
0            1            1       0
1            2            1       0
2            2            2       1
3            2            3       0
4            2            4       0
..         ...          ...     ...
416          2          416       0
417          2          417       0
418          2          418       0
419          2          419       0
420          2          420       0

[421 rows x 3 columns]